apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Chart.Name}}
    service: {{.Chart.Name}}
  name: {{.Chart.Name}}
spec:
  ports:
    - name: web
      port: {{ .Values.service.web.port }}
      protocol: TCP
      targetPort: {{ .Values.service.web.port }}
    - name: kompass
      port: {{ .Values.service.kompass.port }}
      protocol: TCP
      targetPort: {{ .Values.service.kompass.port }}
  selector:
    app: {{.Chart.Name}}
    service: {{.Chart.Name}}
  sessionAffinity: None
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}